### ISSUE TITLE
Installation only shows 1 of many theme versions

### ISSUE THREAD

**Issue by kotutuloro** [benank/everyone.dance#1]
I've got a few different versions of Simply Love saved in my themes.
![Annotation 2021-02-03 124025](https://user-images.githubusercontent.com/18595173/106807769-64bb9880-661e-11eb-96bd-f9095275cbb3.png)

During the everyone.dance installation, Simply Love only shows up once.
![Annotation 2021-02-03 124049](https://user-images.githubusercontent.com/18595173/106808295-0e028e80-661f-11eb-8115-efce910fe16e.png)

When I install it, it corresponds to the Simply Love-v4.9 theme folder (the last folder alphabetically).

Could everyone.dance account for themes with the same display name by also looking at the version info in ThemeInfo.ini?
(Alternatively, I could just stop hoarding old theme versions lmao)

**Comment by benank** [comment]
Thanks for the report! Yeah, I can definitely look into adding version info for the themes as well.

**Comment by geefr** [comment]
I get a similar thing in the in-game theme selection - By default all different versions of a theme have the same name in their themeinfo file, so I end up editing the theme name so it shows in options menu

**Comment by benank** [comment]
[Fixed](https://github.com/benank/everyone.dance/commit/b6ecabc34d6c5782f8055201e43ca04edb0124cf). This + the other fix are included in release 1.0.4.

**Comment by kotutuloro** [comment]
> I get a similar thing in the in-game theme selection - By default all different versions of a theme have the same name in their themeinfo file, so I end up editing the theme name so it shows in options menu

Weirdly enough, the Stepmania theme selection shows the theme's folder name instead of the display name for me, but I'm not really sure why lol

**Comment by kotutuloro** [comment]
> Fixed

Shweet, thank you! Amazing job on this whole project btw!
