### ISSUE TITLE
StepMania 5.1x APPDATA folder name

### ISSUE THREAD

**Issue by MrTwinkles47** [benank/everyone.dance#13]
https://github.com/benank/everyone.dance/blob/98ac2387e3f32c1fd43e53b8f0761204921a967b/src/js/SMEnvironment.js#L103

StepMania 5.1x installs on Windows use the APPDATA folder `%APPDATA%/StepMania 5.1/`.

https://github.com/stepmania/stepmania/releases/tag/v5.1.0-b2

**Comment by benank** [comment]
Thanks, fixed!
