### ISSUE TITLE
everyone.dance.txt file step data returns all zeros while playing a song

### ISSUE THREAD

**Issue by MrTwinkles47** [benank/everyone.dance#29]
**Issue**
everyone.dance player card does not update with step data while playing a song. Song info while in the song selection screen updates just fine.

**Setup**
- everyone.dance 2.1.4
- StepMania 5.3-Outfox (4.9.7GG)
- Simply Love Outfox 4.9.1
- Running everyone.dance on the streaming machine connected over a network share to the StepMania machine.

**Partial Log Dump**
`/////////////////////////////////////////
00:37.902: WARNING: Error playing command:...hemes/Simply-Love-OutFox/BGAnimations/everyone.dance.lua:177: attempt to index a nil value (local 'song')`
`00:37.902: WARNING: /Appearance/Themes/Simply-Love-OutFox/BGAnimations/everyone.dance.lua:177: RefreshActiveSongData(data = ,(for generator) = (null),(for state) = (null),(for control) = 1,_ = 1,pn = PlayerNumber_P1,player_data = (null),song = (null),step_data = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = 0,(*temporary) = (null),(*temporary) = 35,(*temporary) = 35,(*temporary) = 35,(*temporary) = 35,(*temporary) = 2,(*temporary) = Valex's Magical 4-Arrow Adventure 2,(*temporary) = 35,(*temporary) = 35,(*temporary) = 2,(*temporary) = 35,(*temporary) = 50,(*temporary) = 0,(*temporary) = 0,(*temporary) = (null),(*temporary) = (null),(*temporary) = steps_info,(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = W4,(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = steps_info,(*temporary) = :,(*temporary) = W4,(*temporary) = :,(*temporary) = 0,(*temporary) = `
`00:37.902: WARNING: ,(*temporary) =  (local 'song'),(*temporary) = attempt to index a nil value (local 'song'))`
`00:37.902: WARNING: /Appearance/Themes/Simply-Love-OutFox/BGAnimations/everyone.dance.lua:283: unknown(s = (null))
/////////////////////////////////////////`

**Comment by benank** [comment]
Thanks for the detailed report! Will look at this soon and try to reproduce it and see if I can fix it.

**Comment by MrTwinkles47** [comment]
Is there any other info I could grab that would be useful to you? Is there a way to turn on a debug or verbose logging mode?

**Comment by benank** [comment]
I'll let you know! There is a way, but it currently doesn't log much! I'll let you know if I'm unable to reproduce and if I need more information.

**Comment by benank** [comment]
[Fixed!](https://github.com/benank/everyone.dance/commit/93ff05a37f64f29cdc7bf122c6b1ebe0fe304a3e)

**Comment by MrTwinkles47** [comment]
Thanks!
