### ISSUE TITLE
Lua script breaks upon song playback

### ISSUE THREAD

**Issue by JoseVarelaP** [benank/everyone.dance#3]
This is caused as the initial segment of the script (`RefreshActiveSongData()`) looks for the wheel on ScreenGameplay, which doesn't have one. And since it does not have a check to verify that it's there, it can break.

![Captura de Pantalla 2021-02-03 a la(s) 16 24 30](https://user-images.githubusercontent.com/23246027/106817330-554b4800-663c-11eb-9921-96a46d441939.png)

```lua
local mw = SCREENMAN:GetTopScreen():GetChild("MusicWheel")
player_data.ingame = mw == nil
```

Here's a possible solution, that can check for the validation of the object.

```lua
local mw = nil --Initialize the object
if SCREENMAN:GetTopScreen() then -- Verify that the screen exists first before doing anything.
    mw = SCREENMAN:GetTopScreen():GetChild("MusicWheel") --Check that the object is valid.
end
player_data.ingame = mw == nil
```

**Comment by benank** [comment]
Thanks! Included in next version.
