### ISSUE TITLE
Goto button does not always find the right song

### ISSUE THREAD

**Issue by benank** [benank/everyone.dance#8]
If there are multiple songs with the same name installed, it will find the first song by pack alphabetically. It should find the exact song that matches the artist and group/pack as well.

**Comment by MrTwinkles47** [comment]
You might try using the SONG:GetSongDir() along with the SelectSong() lua functions to identify and "goto" the correct song. The SongDir string is how StepMania uniquely identifies every song. This assumes that every player has the song installed in the exact same pack folder and all names are identical.

**Comment by benank** [comment]
Thanks! Yeah people often rename song packs and have them in strange places, so I'll keep the original "Find by name" behavior as a fallback, but it seems to work well!
